### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by time-axis** [falko17/aaoffline#3]
I ran the following command, and it crashed partway through the asset downloading process: 

`aaoffline -p 01c7623f02b452a025dc4511e7e68349eb72ea81 "https://aaonline.fr/player.php?trial_id=140935" "https://aaonline.fr/player.php?trial_id=144209" "https://aaonline.fr/player.php?trial_id=141946" "https://aaonline.fr/player.php?trial_id=145600"`

It generated the following crash report:

```
"name" = "aaoffline"
"operating_system" = "Windows 10.0.19045 (Windows 10 Home) [64-bit]"
"crate_version" = "1.0.0"
"explanation" = '''
Panic occurred in file 'src\download.rs' at line 349
'''
"cause" = 'assertion failed: dir.ends_with("assets")'
"method" = "Panic"
"backtrace" = """
   0:     0x7ff6eeb4848c - <unresolved>
   1:     0x7ff6eebe4576 - <unresolved>
   2:     0x7ff6eea48c1b - <unresolved>
   3:     0x7ff6eeda295d - <unresolved>
   4:     0x7ff6eeda27c2 - <unresolved>
   5:     0x7ff6eeda274f - <unresolved>
   6:     0x7ff6eeda273e - <unresolved>
   7:     0x7ff6eede37f1 - <unresolved>
   8:     0x7ff6eede38ad - <unresolved>
   9:     0x7ff6eead2d7e - <unresolved>
  10:     0x7ff6eeb01673 - <unresolved>
  11:     0x7ff6eeaf592e - <unresolved>
  12:     0x7ff6eea5a536 - <unresolved>
  13:     0x7ff6eeb10745 - <unresolved>
  14:     0x7ff6eeddd97c - <unresolved>
  15:     0x7ffc98247374 - BaseThreadInitThunk
  16:     0x7ffc98e5cc91 - RtlUserThreadStart
"""

```

It seems to occur specifically with any attempt to download trial 140935 and 144209.

**Comment by falko17** [comment]
Oh, I didn't know you could have evidence without any icon (this seems to be what caused the crash). Thank you for the detailed report. I fixed this in #4, I'll try to put out the new version tomorrow.
