### ISSUE TITLE
Space in front of external asset URL interprets it as local

### ISSUE THREAD

**Issue by time-axis** [falko17/aaoffline#8]
So, in this trial:
https://aaonline.fr/player.php?trial_id=141960

Downloading it will fail to download some assets. Of those assets, some are music/sound assets that don't load in AAO's live version either, so that's not the issue here. But one of them, this image: https://imgur.com/SFdcf0Z is not loading, and it should. I get this error:

`[ERROR aaoffline::download] Could not download asset at https://aaonline.fr/ https://i.imgur.com/SFdcf0Z.png: File at ht`

I did some digging, and it seems like the author mistakenly put a space in front of the URL in the editor. AAO still loads the asset, but aaoffline appears to be mistakenly appending https://aaonline.fr/ to the beginning of it. I know this is technically an error on the case developer's part, but since it works on AAO, perhaps aaoffline should ignore spaces at the beginning of URLs as well.

(The case in question might have fixed the space at the beginning since the time of writing this, so this may not replicate when you try it.)

**Comment by falko17** [comment]
> AAO still loads the asset, but aaoffline appears to be mistakenly appending [aaonline.fr](https://aaonline.fr/) to the beginning of it. I know this is technically an error on the case developer's part, but since it works on AAO, perhaps aaoffline should ignore spaces at the beginning of URLs as well.

I agree, I think a good rule of thumb is that if it works in AAO, it should work in aaoffline too. Once again, thanks for the report (amazing how many edge cases you've managed to identify in such a short time span btw), I'll fix this soon.
