### ISSUE TITLE
Error message asks user to run an invalid parameter.

### ISSUE THREAD

**Issue by DeathByAutoscroll** [falko17/aaoffline#9]
Upon detecting identical files, the error message prompts the user to add `--overwrite-existing`. This is invalid, as the correct parameter is `--remove-existing`.

![2024-30-23-27-25](https://github.com/user-attachments/assets/9a8cf903-f3b9-47e5-b1d4-2cfaf1aef77b)
Bruh.

**Comment by DeathByAutoscroll** [comment]
This is version 1.1.1 btw

**Comment by falko17** [comment]
Oops, forgot to update this text when I renamed the parameter. I'll fix it, thanks for the report.
